#library "CROCBARS"

#include "zcommon.acs"

#include "BARLIB.acs"

script "DrawBar_CrocPharaohShotWep" (void) {
	SetOverlayBar(CheckInventory("CrocPharaohCharge"), 100);
}

script "DrawBar_CrocNoiseCrushWep" (void) {
	ACS_NamedExecuteWithResult("DrawBar_NoiseCrushWep");
}

script "DrawBar_CrocCrashBombWep" (void) {
	if(CheckInventory("CrocCrashCooldownFlag")) SetDarkenedBar();
}

script "DrawBar_CrocCopyVisionWep" (void) {
	SetOverlayBar(CheckInventory("CrocCopyVisionTimer"), 40);
}
